---
name: "create-release"

on:
  push:
    branches:
      - "main"

jobs:
  create-release:
    name: "Create Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v1
    
      - name: Setup Node
        uses: "actions/setup-node@v3.5.1"
        with:
          check-latest: true
          
      - name: tsc
        uses: iCrawl/action-tsc@v1
        with:
          build: build/
      
      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r tsab-build.zip build

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "TSAB Build"
          files: |
            LICENSE.txt
            tsab-build.zip
