---
name: "create-release"

on:
  push:
    branches:
      - "main"

jobs:
  create-release:
    name: "Create Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v1
    
      - name: Setup Node
        uses: "actions/setup-node@v3.5.1"
        with:
          check-latest: true
          node-version: '16'
          
      - name: Install Packages
        uses: CultureHQ/actions-yarn@master
        with:
          args: install --ignore-engines
          
      - name: Build Typescript
        uses: alexthemaster/action-build-typescript@v1.3.1
        with:
          branch: 'build'
        
      - name: List All Files In Root
        run: ls -la
      
      - name: ZIP Build Contents
        uses: montudor/action-zip@v1
        with:
          args: zip -r tsab-build.zip . -i build

      - name: Generate New GitHub Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "TSAB Development Build"
          files: |
            LICENSE.txt
            tsab-build.zip
